# Generated by Django 3.0.4 on 2020-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_hod_last_name', models.CharField(max_length=100)),
                ('department_hod_first_name', models.CharField(max_length=100)),
                ('department_hod_other_name', models.CharField(max_length=100)),
                ('department_hod_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
