# Generated by Django 3.0.4 on 2020-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
